### ISSUE TITLE
Disabling this package destroys the tab bar

### ISSUE THREAD

**Issue by bronson** [abe33/atom-table-edit#3]
In the gif, first I open a csv to show that everything is working.

Then I disable table-edit and show the CSV again.  It shows some dark-on-dark unstyled markup.

Then, when I click on the csv's tab, the whole tab bar disappears.  Need to restart Atom to fix it. 

![bug3](https://cloud.githubusercontent.com/assets/1776/9003603/2ec4382e-3724-11e5-97cb-17529eaeafff.gif)

**Comment by abe33** [comment]
Hi, thanks for the feedback, that's clearly a use case I haven't covered yet, one more item in the TODO ;)

**Comment by bronson** [comment]
I was hoping it would be a quick way to get #2.  :)
